{{- range $.Values.owners }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: admin
    user: {{ . }}
  name: namespaceAdmin-{{ regexReplaceAll "\\W+" . "-" }}
  namespace: {{ $.Values.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ . }}
---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  annotations:
    role: edit
    user: {{ . }}
  generation: 1
  name: user-{{ regexReplaceAll "\\W+" . "-" }}-clusterrole-edit
  namespace: {{ $.Values.name }}
spec:
  roleRef:
    kind: ServiceRole
    name: ns-access-istio
  subjects:
  - properties:
      request.headers[kubeflow-userid]: {{ . }}
{{- end }}
