---
# Source: profile/templates/owner-rolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: admin
    user: blair.drummond@cloud.statcan.ca
  name: namespaceAdmin-blair-drummond-cloud-statcan-ca
  namespace: aaw-bar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: blair.drummond@cloud.statcan.ca
---
# Source: profile/templates/owner-rolebindings.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    role: admin
    user: blair.drummond@statcan.gc.ca
  name: namespaceAdmin-blair-drummond-statcan-gc-ca
  namespace: aaw-bar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeflow-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: blair.drummond@statcan.gc.ca
---
# Source: profile/templates/profile.yaml
apiVersion: kubeflow.org/v1
kind: Profile
metadata:
  name: aaw-bar
spec:
  owner:
    kind: User
    name: nobody@statcan.gc.ca
---
# Source: profile/templates/owner-rolebindings.yaml
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  annotations:
    role: edit
    user: blair.drummond@cloud.statcan.ca
  generation: 1
  name: user-blair-drummond-cloud-statcan-ca-clusterrole-edit
  namespace: aaw-bar
spec:
  roleRef:
    kind: ServiceRole
    name: ns-access-istio
  subjects:
  - properties:
      request.headers[kubeflow-userid]: blair.drummond@cloud.statcan.ca
---
# Source: profile/templates/owner-rolebindings.yaml
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  annotations:
    role: edit
    user: blair.drummond@statcan.gc.ca
  generation: 1
  name: user-blair-drummond-statcan-gc-ca-clusterrole-edit
  namespace: aaw-bar
spec:
  roleRef:
    kind: ServiceRole
    name: ns-access-istio
  subjects:
  - properties:
      request.headers[kubeflow-userid]: blair.drummond@statcan.gc.ca
